MONGO_URI = "mongodb://localhost:27017/insta"
SECRET_KEY = "a3a5f8968bd0d4aa03b3d644232e7349"  # Generated by: secrets.token_hex(16) #Replace this in production environment!
UPLOAD_FOLDER = "./static/upload"
ALLOWED_IMG_MIME_EXTENSIONS = "image/png, image/jpeg, image/gif"
ALLOWED_IMG_EXTENSIONS = {'png', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'gif'}
GITHUB_PROFILE_PAGE_URL = 'https://www.github.com/'
NUMBER_OF_SHOWN_POSTS = 50
